- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: KVM Provision role
      include_role:
        name: libvirt-provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        vm_state: "running"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"
