download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-libvirt-1.3.0.tar.gz
format_version: 1.0.0
name: libvirt
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.3.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/libvirt/versions/1.3.0/
